### PR TITLE
Issue #128416 - Fixing failure due to moving absent file 

### PR DESCRIPTION
**Pull request by NordMike**

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
OK, this PR is for AOO42X but we can of course cherry-pick it later for trunk...

Just FTR: This is for Bugzilla Issue
https://bz.apache.org/ooo/show_bug.cgi?id=128416

**Comment by NordMike** [comment]
It's for AOO42X because I'm trying to build upcoming release.

**Comment by Pilot-Pirx** [comment]
Yes, but patches are normally committed top->down.
So first in trunk and then in the branches...

And there is no branch for a release yet, AOO42X is still for development.

**Comment by NordMike** [comment]
Should I rebase it for trunk or is AOO42X OK for now?

**Comment by Pilot-Pirx** [comment]
AOO42X is OK for now.
Can you tell me where this error is to be seen? Is there a log file?

**Comment by Pilot-Pirx** [comment]
OK, this seems to be fixed in trunk for some time:

https://github.com/apache/openoffice/commit/25a457539c4c9ee45d9cc1446a569f5b1532c064#diff-90c5bad7c7b6152ce7d0426fcd732255bf60d14520a136753531608f7c986757

Somehow, it was never backported to AOO42X.

Could you have a look, I think it is identical with your PR.

**Comment by NordMike** [comment]
Yes, it's exactly the same. Backport it, please.

**Comment by Pilot-Pirx** [comment]
Done!
Thanks for finding this.

**Pull request merged**
