### PR TITLE
Add patch for cygwin64

### PR DESCRIPTION
**Pull request by Pilot-Pirx**
Thanks to Damjan for the provided patches!

### CODE REVIEW

**Comment by DamjanJovanovic** [comment]
What's that oowintool change all about? It wasn't part of my 2 commits to trunk.

**Comment by DamjanJovanovic** [comment]
Never mind, that's from https://github.com/apache/openoffice/commit/adb6f5d8a37c5b86304c6f182c17e5b29dcc384a

**Review by DamjanJovanovic — APPROVED** [review]

**Review by cbmarcum — COMMENTED** [review]
I can't really review or test this but since Damjan is good with it and it builds, I'm good with it.

**Comment by Pilot-Pirx** [comment]
My test build was successful, so this can be merged.

**Pull request merged**
