### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by DiGro** [comment]
@jbampton @Pilot-Pirx ,

don't wanna be pickie, but one typo survived the fix:

diff --git a/main/sal/qa/libs2test.txt b/main/sal/qa/libs2test.txt
index 4fad7a4bbd..ffaeb0f267 100644

+# LLA: temporally removed, ==>>  should be:  +# LLA: temporarily removed,

Edited:
sorry guys,  found another one just below the first

//mindy: failed on my RH9,so removed temporally ==>>  temporarily

**Comment by Pilot-Pirx** [comment]
No, this is not a typo:
https://dictionary.cambridge.org/dictionary/english/temporally

But if you find typos, feel free to open a Pull Request. 😉

**Comment by astepukonis** [comment]
“Temporally” is indeed spelled correctly, but it is a wrong word in this context. “Temporarily” should be used instead. The reader is being alerted that the removal will not last for long or forever (see https://dictionary.cambridge.org/dictionary/english/temporarily).

**Comment by Pilot-Pirx** [comment]
Feel free to open a Pull Request.

**Pull request merged**
