### PR TITLE
Add "empty" and "not empty" autofilters

### PR DESCRIPTION
**Pull request by ardovm**
This pull request is an attempt to solve [bug 35578](https://bz.apache.org/ooo/show_bug.cgi?id=35578) by adapting the proposed patch to the current AOO42X sources.

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
Is this already in trunk?

**Comment by pedlino** [comment]
I merged with branch 42X only (or at least that was my intention)
If I messed up, I apologize. I assume it can be undone?

**Comment by Pilot-Pirx** [comment]
No problem, it can be cherry-picked later.
@ardovm: I wonder why this PR was against AOO42X?

**Comment by ardovm** [comment]
> No problem, it can be cherry-picked later. @ardovm: I wonder why this PR was against AOO42X?

I got confused by the bug report requesting a patch to the AOO42X branch. Sorry!

I will cherry-pick it into trunk.

IMHO it does not belong to AOO41X... but we can discuss this on the mailing list.

**Comment by Pilot-Pirx** [comment]
I did a Windows build now, seems to work.
Yes, please cherry-pick it for trunk.

**Pull request merged**
