### PR TITLE
 Visual Programming for OpenOffice

### PR DESCRIPTION
**Pull request by JuanJ67m**
Actually, Excel is the main worksheet for and construction and I think OpenOffice could same, creating nodes for Dynamo BIM nodes to interconnect with Privative software, Pyflow nodes to interconnect with FOSS or Sverchok nodes for Blender.

the result should be automatic documentation if OpenOfficecreates nodes to link all their features to other software and possible integration to any AI.

https://github.com/wonderworks-software/PyFlow

https://github.com/nortikin/sverchok

https://dynamobim.org/download/

here a sample open-source with excel and Dynamo BIM:

https://konradsobon.gitbooks.io/bumblebee-primer/content/110_read_data_from_excel.html

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
What should this PR do?!
The same was opened in LO and is now closed.
I don't see any value here.

**Comment by leginee** [comment]
I think it is a feature request, but I am unsure what to do with it.

**Comment by JuanJ67m** [comment]
> 
> 
> What should this PR do?!
> The same was opened in LO and is now closed.
> I don't see any value here.

was reopened

**Comment by JuanJ67m** [comment]
> 
> 
> I think it is a feature request, but I am unsure what to do with it.

create nodes to allow connect to others FOSS.

**Comment by Pilot-Pirx** [comment]
> > What should this PR do?!
> > The same was opened in LO and is now closed.
> > I don't see any value here.
> 
> was reopened

Yes, from you!
I am sure they will close it again unless you give more details.

**Comment by Pilot-Pirx** [comment]
Merging AOO42X into trunk does not sound like a good idea...

However, if you have a feature request, feel free to discuss it on dev@openoffice.apache.org.

**Pull request closed without merging**
