### PR TITLE
Address bug 128356 and similar ones (duplicated XML attributes)

### PR DESCRIPTION
**Pull request by ardovm**
This is a work-in-progress fix for https://bz.apache.org/ooo/show_bug.cgi?id=128356
Please keep the discussion about the "philosophy" of the patch on Bugzilla.

Code style, variable names, indentation etc. shall be discussed here.

### CODE REVIEW

**Comment by jimjag** [comment]
Is
`
if (!!bAutoStyles)
`
really the best way to format that logical if for https://github.com/apache/openoffice/pull/122/commits/7af97f4fe332f523912f0174635fb94d88995f46 ?

**Comment by ardovm** [comment]
> Is
> `if (!!bAutoStyles)`
> really the best way to format that logical if for [7af97f4](https://github.com/apache/openoffice/commit/7af97f4fe332f523912f0174635fb94d88995f46) ?

Not at all! It's a typo! Thank you for spotting it!

I am planning to test this code later, after changing the assertion into an exception.

**Comment by ardovm** [comment]
Ok, the exception details are shown in non-product builds.
Product builds just show an error message "Error saving the document: write error. Error in writing sub-document content.xml".
I think it is enough to warn the user that the attempt to save the document has failed.
Moreover, if I try to close the document, I am warned that it has not been saved.

Please note that the above was checked with a "hand-inserted" exception, as the documents attached to the reports do not seem to trigger the bug any more.

The PR is IMHO production-ready, but I would like to spend some more time on documentation.

**Comment by ardovm** [comment]
Ok, I am done. Reviews welcome!

**Comment by leginee** [comment]
starting with code review.
I like that you have added comments.

**Comment by dave2wave** [comment]
Is this PR ready? Or, have the changes already been merged in a different PR?

**Comment by ardovm** [comment]
> Is this PR ready? Or, have the changes already been merged in a different PR?

Thank you for checking this! I am still waiting for a review.

I would like to have the proposed _changes_ reviewed first.
Then I'd reshuffle a bit the commits before merging, so they will make more sense -- mainly squashing the WIP and typo correction commits.

**Comment by dave2wave** [comment]
@leginee @ardovm requested your review.

**Comment by leginee** [comment]
Sorry, I forgot about it. I wanted to run the code once. I note in my review the state I have.

**Review by leginee — COMMENTED** [review]
I went through all comments and checked the logic by reading through it.
Code changes look fine. Nothing to add or critizise.

**Comment by Pilot-Pirx** [comment]
With the code now in trunk, do we want to start testing it?

**Comment by leginee** [comment]
Sure.

**Comment by Pilot-Pirx** [comment]
When? ;-)

**Comment by leginee** [comment]
As soon as I find a build ;)

**Comment by Pilot-Pirx** [comment]
https://ci.apache.org/projects/openoffice/install/win/

**Pull request merged**
