### PR TITLE
fix unitialized variables in delivery.pl by treat undef as 0

### PR DESCRIPTION
**Pull request by leginee**
changed:       ../solenv/bin/deliver.pl

### CODE REVIEW

**Comment by leginee** [comment]
I found a small issue in the build logs with undifened variables. Thge fix fixed it for me.
Please test and merge

**Comment by cbmarcum** [comment]
Where can I find the message this fixes during build?

**Review by cbmarcum — COMMENTED** [review]
This change is also included in #85

**Comment by leginee** [comment]
The message appears on build output.
I usually build with the command: `time build --all  > build.log 2> build.err`

The message fixed is 
`Use of uninitialized value $field_a[0] in numeric lt (<) at workspace/AOO/gitbox/main/solenv/bin/deliver.pl line 976.`

I did not open a Bug report. If I shoul just mention it.

**Comment by Pilot-Pirx** [comment]
> This change is also included in #85

Then we can close this PR?

**Comment by leginee** [comment]
Yea I agree. In my work directory I did not separate it I think.

**Comment by ardovm** [comment]
Changes already merged with #85

**Pull request closed without merging**
