### PR TITLE
Allow all https(s) Hyperlinks

### PR DESCRIPTION
**Pull request by dave2wave**
There was some debate on which is best for 4.1.10. Here is the PR should we go this way.

### CODE REVIEW

**Comment by jimjag** [comment]
+1

**Review by cbmarcum — APPROVED** [review]
I can confirm the change now allows https url links to files with any extension, not just those on the whitelist to be passed on to the browser to handle.  Do we need to discuss on dev@ whether we should warn against these as suggested or not before merging?

**Comment by dave2wave** [comment]
Well the CVE was about non-http(s) links. I think we are good to go. Especially since no one engaged to reply.

**Comment by cbmarcum** [comment]
+1

**Comment by cbmarcum** [comment]
Just to be clear this also allows any extension with HTTP also.  Just wanted to make sure that was the intent.

**Comment by dave2wave** [comment]
Yes. That was the intent. Maybe in 4.2.0 we discussing forcing http to https as one of our hyperlink security settings.

**Comment by cbmarcum** [comment]
I figured so but I thought I should check.  I've seen people get surprised by the fall though behavior in a switch case and I didn't check for HTTP before.

**Pull request merged**
