### PR TITLE
Cppuhelper compiler warning fixed

### PR DESCRIPTION
**Pull request by leginee**
I cleaned the module of all compiler warnings

### CODE REVIEW

**Review by cbmarcum — APPROVED** [review]
I confirm that trunk builds without the warnings and runs afterwards.

**Review by ardovm — APPROVED** [review]
This PR looks good to me. I could merge it into current trunk, build and run AOO.

I will merge it in 24 hours, if no one raises any objections.

**Comment by Pilot-Pirx** [comment]
Does this PR supersede #84 ?
Then we can close it as well, when this is merged.

**Comment by ardovm** [comment]
> Does this PR supersede #84 ?
> Then we can close it as well, when this is merged.

I think so, because commits be18c4b4c58709f70c68d94437d5aba6ff5893db (#84) and ad38db1599c3ff6616b2f21915332419b6a6079c (this PR) look exactly the same.

I will take care of that.

**Comment by ardovm** [comment]
Rebased and merged

**Pull request closed without merging**
