### PR TITLE
Update bridges to fix build on FreeBSD PowerPC64

### PR DESCRIPTION
**Pull request by lenoil98**
The bridges were updated to allow build on powerpc64 with default (clang) compiler.

### CODE REVIEW

**Comment by dave2wave** [comment]
I think we need a review from a FreeBSD builder from downstream.

**Comment by pedlino** [comment]
> I think we need a review from a FreeBSD builder from downstream.

I don't have FreeBSD or a PowerPC... Sorry!

**Comment by ardovm** [comment]
> I think we need a review from a FreeBSD builder from downstream.

Yes! Possibly someone with a PowerPC...

In the meantime, we could check that this patch does not break compilation on other architectures.

@lenoil98 thank you for your contribution. Could you please state that it can be used under the Apache License, version 2.0?

**Comment by ardovm** [comment]
We also need Apache license header on new files, please

**Comment by lenoil98** [comment]
Updated files with Apache license header in new files.

**Comment by ardovm** [comment]
...maybe @pgiffuni could help here?

**Comment by DonLewisFreeBSD** [comment]
On  3 Nov, Arrigo Marchiori wrote:
> 
> ...maybe @pgiffuni could help here?
> 

Curtis Hamilton ***@***.***> filed this FreeBSD bug report and
recently attached PowerPC64 patches. I haven't compared them to the
patches in this MR.  

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251417

**Comment by ardovm** [comment]
For what it's worth, I verified that this PR does not seem to affect Linux and Windows builds.

**Comment by pgiffuni** [comment]
I don't have PowerPC either but Curtis Hamilton is pretty trustrworthy and has contributed changes for FreeBSD-PPC in the past.

**Review by pgiffuni — APPROVED** [review]

**Pull request merged**
