### PR TITLE
Bundle418

### PR DESCRIPTION
**Pull request by DonLewisFreeBSD**
Cherry pick bundled software upgrades from AOO42X:

Upgrade ext_libraries:
        apr
        apr-util
        hunspell-1.3.3
        ratscan

Upgrade main modules:
        apache-commons
        beanshell
        libxml2
        libxslt
        more_fonts
        nss
        python
        redland

external_deps.lst cleanups

### CODE REVIEW

**Review by Pilot-Pirx — COMMENTED** [review]
My first build on Windows was successful. A short test didn't show any problems.
I will do another build with release configuration (and MozillaBuild 3.3) now.

**Review by Pilot-Pirx — APPROVED** [review]
My second build for Windows with release configuration went well. Additionally I built with MozillaBuild 3.3. instead of 2.2.0. Installation went smooth , no problems detected so far.

**Comment by Pilot-Pirx** [comment]
I would really like to get this PR in AOO418.
@jimjag: But for macOS there are still adjustments to be made?

**Review by cbmarcum — APPROVED** [review]
Built and tested PR on CentOS 7 VM with JDK 7 and had no issues.

**Pull request merged**
