### PR TITLE
JDK8 ODK

### PR DESCRIPTION
**Pull request by DonLewisFreeBSD**
Correct javadoc comments to unbreak --enable-odk build with JDK 8 or newer

### CODE REVIEW

**Review by Pilot-Pirx — COMMENTED** [review]
My Windows test builds (incl. SDK) were successful.
But when building with Java 8 (Oracle) an installed Java 7 is not detected by AOO.
Since we still are building our releases with Java 7 this would be a minor regression for our users.

**Review by cbmarcum — APPROVED** [review]
built PR with JDK 8 on CentOS 7 and everything worked as expected.  Ran automated BVT tests and all 46 were passed.

**Comment by DonLewisFreeBSD** [comment]
> My Windows test builds (incl. SDK) were successful.
> But when building with Java 8 (Oracle) an installed Java 7 is not detected by AOO.
> Since we still are building our releases with Java 7 this would be a minor regression for our users.

I believe the problem is present without the patch, but the build with Java 8 would have to be done w/o the SDK.

I will try to dig into this.

**Comment by Pilot-Pirx** [comment]
> I believe the problem is present without the patch, but the build with Java 8 would have to be done w/o the SDK.
> 
> I will try to dig into this.

Yes, I think this is independent of the patch. A general problem we have with 4.1.x
Building AOO 4.2.x with Java 8 works as expected.

**Comment by DonLewisFreeBSD** [comment]
> > I believe the problem is present without the patch, but the build with Java 8 would have to be done w/o the SDK.
> > I will try to dig into this.
> 
> Yes, I think this is independent of the patch. A general problem we have with 4.1.x
> Building AOO 4.2.x with Java 8 works as expected.

Which is odd.  A while back I compared the detection code between the two branches and they appeared to be identical.

**Comment by cbmarcum** [comment]
I went back and checked my build and I can confirm what Matthias found about Java 7 was not discovered when I built with Java 8. But I don't think that is an issue for this PR.

**Pull request merged**
