### PR TITLE
Translate string name STR_UNBENANNT

### PR DESCRIPTION
**Pull request by Pilot-Pirx**

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
We should really get rid of the German parts in our source!

Beware: Because of the string changes this can only be merged when we have a working translation process and are able to provide updated SDF files shortly after.

**Comment by Mechtilde** [comment]
Please give me a hint if you want a new SDF-File esp imported into 
Pootle for version 4.2.X



Am 07.05.23 um 12:13 schrieb Matthias Seidel:
> We should really get rid of the German parts in our source!
> 
> Beware: Because of the string changes this can only be merged when we have a working translation process and are able to provide updated SDF files shortly after.
> 

--

**Comment by Pilot-Pirx** [comment]
There have been a lot of string changes since the last import/export.
Has the process been properly tested?

If we merge this PR (and PR 168) we would need SDF files for all languages.

**Comment by Mechtilde** [comment]
There is still Ubuntu 18.04. so I have no idea what I should test.

Am 07.05.23 um 16:57 schrieb Matthias Seidel:
> There have been a lot of string changes since the last import/export.
> Has the process been properly tested?
> 
> If we merge this PR (and PR 168) we would need SDF files for all languages.
>

**Comment by Pilot-Pirx** [comment]
Test if the new strings are imported and exported OK.

Last time we had a big mess.

**Comment by Mechtilde** [comment]
I have no idea why it happens. so I have no idea how I can produce the 
tests.

Therefore I need support and help.


Am 07.05.23 um 18:18 schrieb Matthias Seidel:
> Test if the new strings are imported and exported OK.
> 
> Last time we had a big mess.
>

**Comment by Pilot-Pirx** [comment]
That's what we have dev@ for... ;-)

**Pull request closed without merging**
