### PR TITLE
Scons build

### PR DESCRIPTION
**Pull request by leginee**
Hello Damjan,

I forgot to commit to the tree. Here are my linux profile for review.
It is based on the freeBSD one.

All the best
Peter

### CODE REVIEW

**Comment by leginee** [comment]
Aww I merged some trunk commits too :face_with_head_bandage:

**Review by DamjanJovanovic — APPROVED** [review]
Thank you, it's a start. The gbuild file for Linux has more stuff than FreeBSD so we should still do a separate comparison against main/solenv/gbuild/platform/linux.mk

**Comment by leginee** [comment]
Cool, Okay I will have a look.
thx for the pointer.
I will update the pull request. So lets leave it open for now.

**Comment by ardovm** [comment]
Force-pushed away unrelated commits.
Merging as per thread on dev@

**Pull request merged**
