### PR TITLE
Attempt to update Boost to version 1.79

### PR DESCRIPTION
**Pull request by pgiffuni**
Newer versions of boost will require a C++14 enabled compiler to build. Older versions are really painful to patch to work with newer compilers. This version includes pretty much all the patches required from the previous versions so are expected to build without much trouble with most compilers.

While here also bring some really nice headers and libraries we sloppily never really cared to install, but could be really useful to extend AOO's functionality.

Mostly tested on FreeBSD, which still fails due to unrelated compiler pickiness.  Mileage may vary on Windows and OS/2: there is no TR1 support any more..

### CODE REVIEW

**Comment by pgiffuni** [comment]
For some reason the the last commit includes a change that was not meant to be part of the PR.
It re-enables some type conversions in Boost for higher precision, No idea why it made it here but you can take it as well.

**Comment by Pilot-Pirx** [comment]
=============
Building module sal
=============

Entering /cygdrive/c/Source/openoffice/main/sal/inc


Entering /cygdrive/c/Source/openoffice/main/sal/rtl/source

Making:    all_cpprtl.dpslo
Making:    all_cpprtl.dpobj
--- ALWAYSDBGFILES ---
--- ALWAYSDBGFILES OVER ---

Entering /cygdrive/c/Source/openoffice/main/sal/textenc

Making:    all_textenc.dpslo
Making:    all_textenc.dpobj

Entering /cygdrive/c/Source/openoffice/main/sal/osl/all

Compiling: sal/osl/all/filepath.c
Compiling: sal/osl/all/debugbase.cxx
C:/Source/openoffice/main/solver/450/wntmsci12.pro/inc\boost/config.hpp(35) : fatal error C1083: Cannot open include file: 'boost/config/detail/select_compiler_config.hpp': No such file or d
irectory
dmake:  Error code 2, while making '../../wntmsci12.pro/obj/debugbase.obj'

1 module(s):
        sal
need(s) to be rebuilt

Reason(s):

ERROR: error 65280 occurred while making /cygdrive/c/Source/openoffice/main/sal/osl/all

When you have fixed the errors in that module you can resume the build by running:

        build --from sal

**Comment by pgiffuni** [comment]
I  think found the issue, on file openoffice/main/boost/prj/d.lst line 110, please insert:
mkdir: %_DEST%\inc%_EXT%\boost\config\detail
(clean and rebuild boost)

**Comment by pgiffuni** [comment]
More header issues detected .... changes coming.

**Comment by pgiffuni** [comment]
Should work now: only issue is that patch-clang doesnt apply cleanly.

**Comment by Pilot-Pirx** [comment]
It still breaks in module /sal:

---

Entering /cygdrive/c/Source/openoffice/main/sal/osl/all

Compiling: sal/osl/all/debugbase.cxx
C:/Source/openoffice/main/solver/450/wntmsci12.pro/inc\boost/ref.hpp(15) : fatal error C1083: Cannot open include file: 'boost/core/ref.hpp': No such file or directory
dmake:  Error code 2, while making '../../wntmsci12.pro/obj/debugbase.obj'

1 module(s):
        sal
need(s) to be rebuilt

Reason(s):

ERROR: error 65280 occurred while making /cygdrive/c/Source/openoffice/main/sal/osl/all

When you have fixed the errors in that module you can resume the build by running:

        build --from sal

**Comment by pgiffuni** [comment]
I committed another fix.. sorry .. it is very easy to make mistakes in this process :(

**Comment by Pilot-Pirx** [comment]
No problem! I will try another build.
But maybe you could convert this PR to a Draft?

**Comment by Pilot-Pirx** [comment]
Entering /cygdrive/c/Source/openoffice/main/sal/osl/all

Compiling: sal/osl/all/debugbase.cxx
C:/Source/openoffice/main/solver/450/wntmsci12.pro/inc\boost/bind/bind.hpp(30) : fatal error C1083: Cannot open include file: 'boost/bind/detail/result_traits.hpp': No such file or directory
dmake:  Error code 2, while making '../../wntmsci12.pro/obj/debugbase.obj'

1 module(s):
        sal
need(s) to be rebuilt

Reason(s):

ERROR: error 65280 occurred while making /cygdrive/c/Source/openoffice/main/sal/osl/all

When you have fixed the errors in that module you can resume the build by running:

        build --from sal

**Comment by Pilot-Pirx** [comment]
Now it goes further but breaks in o3tl:

=============
Building module o3tl
=============

Entering /cygdrive/c/Source/openoffice/main/o3tl/prj

cd .. && make -s -r -j1   && make -s -r deliverlog
[ build CXX ] o3tl/qa/cow_wrapper_clients
cow_wrapper_clients.cxx
C:/Source/openoffice/main/solver/450/wntmsci12.pro/inc\boost/preprocessor/tuple/rem.hpp(22) : fatal error C1083: Cannot open include file: 'boost/preprocessor/tuple/detail/is_single_return.h
pp': No such file or directory
[ build PKG ] o3tl_inc
[ build MOD ] o3tl
[ build ALL ] top level modules: o3tl
[ build ALL ] loaded modules: o3tl
make: *** No rule to make target '/cygdrive/c/Source/openoffice/main/solver/450/wntmsci12.pro/workdir/CxxObject/o3tl/qa/cow_wrapper_clients.o', needed by '/cygdrive/c/Source/openoffice/main/solver/450/wntmsci12.pro/workdir/LinkTarget/GoogleTest/o3tl_test.exe'.  Stop.
dmake:  Error code 2, while making 'all'

1 module(s):
        o3tl
need(s) to be rebuilt

Reason(s):

ERROR: error 65280 occurred while making /cygdrive/c/Source/openoffice/main/o3tl/prj

When you have fixed the errors in that module you can resume the build by running:

        build --from o3tl

**Comment by Pilot-Pirx** [comment]
And cppu:

=============
Building module cppu
=============

Entering /cygdrive/c/Source/openoffice/main/cppu/inc


Entering /cygdrive/c/Source/openoffice/main/cppu/source/LogBridge


Entering /cygdrive/c/Source/openoffice/main/cppu/source/UnsafeBridge


Entering /cygdrive/c/Source/openoffice/main/cppu/source/AffineBridge


Entering /cygdrive/c/Source/openoffice/main/cppu/source/helper/purpenv


Entering /cygdrive/c/Source/openoffice/main/cppu/source/uno


Entering /cygdrive/c/Source/openoffice/main/cppu/source/typelib


Entering /cygdrive/c/Source/openoffice/main/cppu/source/threadpool

Compiling: cppu/source/threadpool/threadpool.cxx
C:/Source/openoffice/main/solver/450/wntmsci12.pro/inc\boost/exception/exception.hpp(9) : fatal error C1083: Cannot open include file: 'boost/assert/source_location.hpp': No such file or dir
ectory
dmake:  Error code 2, while making '../../wntmsci12.pro/slo/threadpool.obj'

1 module(s):
        cppu
need(s) to be rebuilt

Reason(s):

ERROR: error 65280 occurred while making /cygdrive/c/Source/openoffice/main/cppu/source/threadpool

When you have fixed the errors in that module you can resume the build by running:

        build --from cppu

**Comment by pgiffuni** [comment]
Huge thanks for your incredible patience. I should be reproducing at least some of these in my platform but unfortunately I am seeing other types of breakage. I get past boost but not after configmgr vcl.

These take me few time to fix but they likely take you long to catch: my recommendation is to clean just the boost build and start a build --from-boost each time. That should cut the build time just to the necessary. 

Thanks again for the patience and sorry that it has been such an unexpectedly error-prone process!

**Comment by pgiffuni** [comment]
I think with some more patience (not too much more hopefully) we could get this working on Windows without much trouble but I fear this may bring trouble to other platforms. Let's take some time before merging this change, And let's check with Don Lewis as well.

**Comment by Pilot-Pirx** [comment]
"Fortunately" the build always broke within the first hour. ;-)
I will try another build after we have 4.1.15 released today!

**Comment by pgiffuni** [comment]
Let's cancel this .. I will be providing a better suited set of changes.

**Pull request closed without merging**
