### PR TITLE
Fix for Issue 114497

### PR DESCRIPTION
**Pull request by oooforum**
Thanks to hanya for this patch

### CODE REVIEW

**Comment by cbmarcum** [comment]
Hi Cyril, could you provide some simple steps we can use to test this before and after the fix for those who have not used the mail merge feature before.

**Comment by oooforum** [comment]
Simple, read the BZ report https://bz.apache.org/ooo/show_bug.cgi?id=114497 and apply instructions from comment #37
Before, we can not use smtp with SSL protocol (like GMail account).
After, access works.

**Comment by oooforum** [comment]
Somebody can push it this fix? 
It will be fine to have this in the next builds.

**Review by ardovm — APPROVED** [review]
The code looks good to me.

**Pull request merged**
