### PR TITLE
Switch to icu 4.2.1

### PR DESCRIPTION
**Pull request by ardovm**
The first step towards an up-to-date icu into the OpenOffice sources.

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
Builds fine on Windows, please test:
https://www.dropbox.com/scl/fi/ljw37r40h21pnlttd2xi8/Apache_OpenOffice_4.5.0_Win_x86_install_en-US_icu.exe?rlkey=xk673b3mu7uos8h7q9x4imo28&st=sscnvzb0&dl=0

**Comment by ardovm** [comment]
I forgot to test the branch on MacOS. I will add another commit to fix compilation on that platform.

**Comment by ardovm** [comment]
This PR is now meant to be squashed and merged

**Comment by Pilot-Pirx** [comment]
I re-built for Windows (see link above), no problems.

**Pull request merged**
