### PR TITLE
Python2718

### PR DESCRIPTION
**Pull request by leginee**
As announced the commit for review and further testing.

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
Just FYI, these are the changes between 2.7.17 and 2.7.18:

https://github.com/python/cpython/compare/v2.7.17...v2.7.18

**Comment by Pilot-Pirx** [comment]
My Windows Test Build was successful.
Python scripts could be executed without problems.

**Comment by Pilot-Pirx** [comment]
Anyone else wanting to review this?

**Comment by Pilot-Pirx** [comment]
Come on, this is no rocket science!

**Review by cbmarcum — APPROVED** [review]
I have built this PR on CentOS 7 and tested.  I tested a few of the included Python macros and they ran.  I wrote a Python macro that displayed the Python version and it ran properly.

**Comment by cbmarcum** [comment]
A test macro..

```python
import sys
 
def HelloVersionPython( ):
    """Prints the Python version into the current document"""
    #get the doc from the scripting context which is made available to all scripts
    model = XSCRIPTCONTEXT.getDocument()
    text = model.Text
    cursor = text.createTextCursor()
    text.insertString( cursor, sys.version, 0 )`
```

**Comment by Pilot-Pirx** [comment]
With https://github.com/apache/openoffice/commit/26aca12f509e5c739c98db9ce5641a2c5feecea7 this PR is now obsolete?

**Comment by DonLewisFreeBSD** [comment]
Yes, I think so.

Why was this never merged?

**Comment by Pilot-Pirx** [comment]
I really don't know... ;-)

**Pull request closed without merging**
