### PR TITLE
Update srcrelease.xml to exclude certain files from Source build

### PR DESCRIPTION
**Pull request by Pilot-Pirx**

### CODE REVIEW

**Comment by Pilot-Pirx** [comment]
See:
https://bz.apache.org/ooo/show_bug.cgi?id=127544

**Review by ardovm — CHANGES_REQUESTED** [review]
You are excluding all files named `.log`. You probably wanted to exclude all files _ending_ in `.log`? If so, the correct entry should be `**/*.log`

BTW, well spotted the missing comma after `**.svn`!

**Comment by ardovm** [comment]
It is also not very clear to me, if the other spurious files from the bug report are still included.
If so, shall we also add exclusions for them in this PR?

**Comment by Pilot-Pirx** [comment]
Thanks! My understanding is that we don't want to bundle any log, so I will change it accordingly.

**Review by ardovm — APPROVED** [review]
This looks good to me.
Any other files to exclude?

**Comment by Pilot-Pirx** [comment]
I think Andrea had some...
If he can add them we could close the Bugzilla issue.

**Comment by Pilot-Pirx** [comment]
I think this issue should be fixed before the next release.
So any additions are welcome!

**Comment by Pilot-Pirx** [comment]
If there are no additions needed I will merge this PR in the next days.
Then it will be included in 4.2.0-Dev4 and 4.1.14.

**Pull request merged**
